version: "3"

services:

  elastic-auth:
    image: nginx:1.21.4
    restart: unless-stopped
    volumes:
      - ./nginx-elastic.conf:/etc/nginx/nginx.conf
      # - ./elasticsearch/.htpasswd:/etc/nginx/.htpasswd
      ## For multiple users: uncomment this line to mount a pre-generated .htpasswd 
      # - ./.htpasswd:/etc/nginx/.htpasswd
      # Generate it with: htpasswd -Bbn elastic yourpassword > elasticsearch/.htpasswd
    environment:
      - AUTH_USER=${OXIGRAPH_USER:-oxigraph}
      - AUTH_PASSWORD=${OXIGRAPH_PASSWORD:-oxigraphy}
      - VIRTUAL_HOST=elastic.index.semanticscience.137.120.31.148.nip.io
      - LETSENCRYPT_HOST=elastic.index.semanticscience.137.120.31.148.nip.io
      # - VIRTUAL_HOST=elastic.index.semanticscience.org
      # - LETSENCRYPT_HOST=elastic.index.semanticscience.org}
      - VIRTUAL_PORT=9200
    entrypoint: "bash -c 'echo -n $AUTH_USER: >> /etc/nginx/.htpasswd && echo $AUTH_PASSWORD | openssl passwd -stdin -apr1 >> /etc/nginx/.htpasswd && /docker-entrypoint.sh nginx'"
  

  elasticsearch:
    # image: elasticsearch:7.16.1
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      # - xpack.security.enabled=true
      # - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - /data/shapes-of-you/elasticsearch:/usr/share/elasticsearch/data
      # Fix permissions in host: sudo chown -R 1000:0 /data/shapes-of-you/elasticsearch



  oxigraph:
    image: ghcr.io/oxigraph/oxigraph:latest
    restart: unless-stopped
    ## To build from local source code:
    # build:
    #   context: .
    #   dockerfile: server/Dockerfile
    volumes:
      - /data/shapes-of-you/oxigraph:/data

  oxigraph-auth:
    image: nginx:1.21.4
    restart: unless-stopped
    environment:
      - AUTH_USER=${OXIGRAPH_USER:-oxigraph}
      - AUTH_PASSWORD=${OXIGRAPH_PASSWORD:-oxigraphy}
      - VIRTUAL_HOST=${VIRTUOSO_URL:-data.index.semanticscience.org}
      - LETSENCRYPT_HOST=${VIRTUOSO_URL:-data.index.semanticscience.org}
      - VIRTUAL_PORT=7878
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    # ports:
    #   - "7878:7878"
    entrypoint: "bash -c 'echo -n $AUTH_USER: >> /etc/nginx/.htpasswd && echo $AUTH_PASSWORD | openssl passwd -stdin -apr1 >> /etc/nginx/.htpasswd && /docker-entrypoint.sh nginx'"



  # NOT USED anymore
  virtuoso:
    container_name: shapes-of-you-virtuoso
    image: openlink/virtuoso-opensource-7:latest
    # image: markw/ldp_server:latest
    # image: tenforce/virtuoso:latest
    # https://hub.docker.com/r/markw/ldp_server

    # https://community.openlinksw.com/t/permissions-on-ldp-containers-and-resources/290/14
    # Download VAD packages: ODS Framework and Briefcase
    # http://download3.openlinksw.com/index.html?prefix=uda/vad-vos-packages/7.2/
    restart: unless-stopped
    volumes:
      - /data/shapes-of-you/virtuoso:/database
      # - /data/shapes-of-you/virtuoso:/data
    environment:
      # Deployed using https://github.com/nginx-proxy
      # - VIRTUAL_HOST=${VIRTUOSO_URL}
      # - LETSENCRYPT_HOST=${VIRTUOSO_URL}
      - VIRTUAL_HOST=virtuoso.index.semanticscience.137.120.31.148.nip.io
      - LETSENCRYPT_HOST=virtuoso.index.semanticscience.137.120.31.148.nip.io
      - VIRTUAL_PORT=8890
      # http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFPerformanceTuning
      # http://docs.openlinksw.com/virtuoso/rdfperfgeneral/
      # https://github.com/tenforce/docker-virtuoso/blob/master/virtuoso.ini
      - DBA_PASSWORD=${VIRTUOSO_PASSWORD:-dba}
      - DAV_PASSWORD=${VIRTUOSO_PASSWORD:-dba}
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=https://w3id.org/um/shapes-of-you
      # - VIRT_URIQA_DynamicLocal=1
      # - VIRT_URIQA_DefaultHost=localhost:8890
      - VIRT_URIQA_DefaultHost=${VIRTUOSO_URL}
      # - VIRT_Parameters_DirsAllowed=., /data, /usr/local/virtuoso-opensource/share/virtuoso/vad, /usr/local/virtuoso-opensource/var/lib/virtuoso/db
      - VIRT_Database_ErrorLogLevel=2 # default: 7 is maximum logs
      - VIRT_HTTPServer_HTTPThreadSize=280000
      # Large dataset config
      - VIRT_SPARQL_ResultSetMaxRows=1048576
      - VIRT_SPARQL_MaxQueryCostEstimationTime=200000
      - VIRT_SPARQL_MaxQueryExecutionTime=1000000
      - VIRT_Database_MaxCheckpointRemap=125000
      - VIRT_TempDatabase_MaxCheckpointRemap=125000
      - VIRT_Parameters_TempDBSize=100000000
      - VIRT_Parameters_NumberOfBuffers=5450000 # For 64G systems
      - VIRT_Parameters_MaxDirtyBuffers=4000000
      # - VIRT_Parameters_NumberOfBuffers=10880000 # For 128G systems
      # - VIRT_Parameters_MaxDirtyBuffers=8000000
      - VIRT_SPARQL_ShortenLongURIs=1
      - VIRT_SPARQL_MaxCacheExpiration=1
      - VIRT_SPARQL_ExternalQuerySource=1
      - VIRT_SPARQL_ExternalXsltSource=1
    # ports:
    #   - 8890:8890
    #   - 1111:1111

  # webapp:
  #   build: ./website
  #   container_name: projects
  #   ports:
  #     - 5000:5000